pub mod adxl345;
pub use adxl345::{
    Adxl345Minimal, Adxl345Full,
    INT_DATA_READY, INT_SINGLE_TAP, INT_DOUBLE_TAP, INT_ACTIVITY, INT_INACTIVITY,
    INT_FREE_FALL, INT_WATERMARK, INT_OVERRUN,
    FIFO_BYPASS, FIFO_FIFO, FIFO_STREAM, FIFO_TRIGGER,
    WAKEUP_8_HZ, WAKEUP_4_HZ, WAKEUP_2_HZ, WAKEUP_1_HZ,
};

pub mod bma150;
pub use bma150::{
    Bma150Minimal, Bma150Full,
    SOURCE_LOW_G, SOURCE_HIGH_G, SOURCE_ANY_MOTION, SOURCE_ALERT, SOURCE_NEW_DATA,
    STATUS_LG_LATCHED, STATUS_HG_LATCHED,
};

pub mod bma180;
pub use bma180::{
    Bma180Minimal, Bma180Full,
    SOURCE_SLOPE, SOURCE_TAP,
    STATUS_HIGH_G, STATUS_LOW_G, STATUS_SLOPE, STATUS_TAP,
    STATUS_X_FIRST, STATUS_Y_FIRST, STATUS_Z_FIRST,
};

pub mod adxl362;
pub use adxl362::{
    Adxl362Minimal, Adxl362Full,
    SOURCE_DATA_READY, SOURCE_FIFO_READY, SOURCE_FIFO_WATERMARK, SOURCE_FIFO_OVERRUN,
    SOURCE_ACT, SOURCE_INACT, SOURCE_AWAKE,
    NOISE_NORMAL, NOISE_LOW, NOISE_ULTRALOW,
    LINKLOOP_DEFAULT, LINKLOOP_LINKED, LINKLOOP_LOOP,
    FIFO_DISABLED, FIFO_OLDEST_SAVED, FIFO_STREAM as ADXL362_FIFO_STREAM, FIFO_TRIGGERED,
    AXIS_X, AXIS_Y, AXIS_Z, AXIS_TEMP,
};