pub mod adxl345;
pub use adxl345::{
    Adxl345Minimal, Adxl345Full,
    INT_DATA_READY, INT_SINGLE_TAP, INT_DOUBLE_TAP, INT_ACTIVITY, INT_INACTIVITY,
    INT_FREE_FALL, INT_WATERMARK, INT_OVERRUN,
    FIFO_BYPASS, FIFO_FIFO, FIFO_STREAM, FIFO_TRIGGER,
    WAKEUP_8_HZ, WAKEUP_4_HZ, WAKEUP_2_HZ, WAKEUP_1_HZ,
};

pub mod adxl362;
pub use adxl362::{
    Adxl362Minimal, Adxl362Full,
    SOURCE_DATA_READY, SOURCE_FIFO_READY, SOURCE_FIFO_WATERMARK, SOURCE_FIFO_OVERRUN,
    SOURCE_ACT, SOURCE_INACT, SOURCE_AWAKE,
    NOISE_NORMAL, NOISE_LOW, NOISE_ULTRALOW,
    LINKLOOP_DEFAULT, LINKLOOP_LINKED, LINKLOOP_LOOP,
    FIFO_DISABLED, FIFO_OLDEST_SAVED, FIFO_STREAM, FIFO_TRIGGERED,
    AXIS_X, AXIS_Y, AXIS_Z, AXIS_TEMP,
};