pub mod adxl345;
pub use adxl345::{
    Adxl345Minimal, Adxl345Full,
    INT_DATA_READY, INT_SINGLE_TAP, INT_DOUBLE_TAP, INT_ACTIVITY, INT_INACTIVITY,
    INT_FREE_FALL, INT_WATERMARK, INT_OVERRUN,
    FIFO_BYPASS, FIFO_FIFO, FIFO_STREAM, FIFO_TRIGGER,
    WAKEUP_8_HZ, WAKEUP_4_HZ, WAKEUP_2_HZ, WAKEUP_1_HZ,
};