[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "periph"
version = "1.2.1"
description = "Peripheral chip drivers for MicroPython, CircuitPython, and Linux"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
include = ["periph*"]
