import spidev

from .base import Transport


def _encode(data):
    out = bytearray(len(data) * 3 + 16)
    for i, byte in enumerate(data):
        bits = 0
        for bit in range(7, -1, -1):
            bits = (bits << 3) | (0b110 if (byte >> bit) & 1 else 0b100)
        out[i * 3:(i + 1) * 3] = bits.to_bytes(3, "big")
    return bytes(out)


class NeoPixelTransport(Transport):
    """NeoPixel transport for Linux (wraps spidev, uses /dev/spidevBUS.DEVICE).

    Encodes pixel data as WS2812B-compatible SPI bitstream at 2.4 MHz, mode 0.
    The reset low pulse (50+ us) is generated by the 16 trailing zero bytes.

    Args:
        bus_num: SPI bus number (opens /dev/spidevBUS.DEVICE).
        device_num: Chip-select line on the bus.
    """

    def __init__(self, bus_num, device_num):
        self._spi = spidev.SpiDev()
        self._spi.open(bus_num, device_num)
        self._spi.mode = 0
        self._spi.max_speed_hz = 2_400_000

    def write(self, data):
        """Encode and transmit pixel data, then hold MOSI low for reset.

        Args:
            data: Bytes to send (3 bytes per RGB pixel, 4 bytes per RGBW pixel).
        """
        encoded = _encode(data)
        self._spi.xfer2(list(encoded))

    def close(self):
        """Release the spidev device."""
        self._spi.close()